# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: task-manager
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: task-manager
#   template:
#     metadata:
#       labels:
#         app: task-manager
#     spec:
#       containers:
#         - name: task-manager
#           image: task-manager:2.0
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 3000


apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-manager
  namespace: task-manager

spec:
  replicas: 2

  selector:
    matchLabels:
      app: task-manager

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: task-manager

    spec:
      containers:

        - name: task-manager

          image: karthikp123kar/task-manager:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"

            - name: APP_VERSION
              value: "1.0.0"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000

            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
